// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package MergeSort

import (
	"reflect"
	"testing"
)

func TestMergeSort_bddcaab54b(t *testing.T) {
	testCases := []struct {
		name     string
		input    []int
		expected []int
	}{
		{
			name:     "Test case 1: Normal scenario",
			input:    []int{5, 4, 3, 2, 1},
			expected: []int{1, 2, 3, 4, 5},
		},
		{
			name:     "Test case 2: Edge case with empty input",
			input:    []int{},
			expected: []int{},
		},
		{
			name:     "Test case 3: Input with negative numbers",
			input:    []int{5, -4, 3, -2, 1},
			expected: []int{-4, -2, 1, 3, 5},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := mergeSort(tc.input)
			if !reflect.DeepEqual(result, tc.expected) {
				t.Errorf("mergeSort(%v) = %v; expected %v", tc.input, result, tc.expected)
			} else {
				t.Logf("Test %v passed", tc.name)
			}
		})
	}
}
