// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

func handleKeyboardInput(drone *tello.Driver) func(e *keyboard.KeyEvent) {
	return func(e *keyboard.KeyEvent) {
		switch e.Key {
		case keyboard.A:
			drone.Left(10)
		case keyboard.D:
			drone.Right(10)
		// TODO: Add more cases for different keys
		default:
			fmt.Println("Unknown key")
		}
	}
}
