// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package main

import (
	"testing"

	"gobot.io/x/gobot"
	"gobot.io/x/gobot/platforms/dji/tello"
)

// TestResetDronePostion_b5a7be9e74 tests the resetDronePosition function
func TestResetDronePostion_b5a7be9e74(t *testing.T) {
	var drone *tello.Driver

	// Create a new instance of drone
	droneAdaptor := tello.NewAdaptor()
	drone = tello.NewDriver(droneAdaptor)

	// Reset drone position
	resetDronePostion(drone)

	// Check if drone's position is reset
	if drone.CurrentPosition() != [3]float64{0, 0, 0} {
		t.Log("Drone position: ", drone.CurrentPosition())
		t.Error("Failed to reset drone position")
	} else {
		t.Log("Success: Drone position reset correctly")
	}

	// Check if drone's rotation is reset
	if drone.CurrentRotation() != [3]float64{0, 0, 0} {
		t.Log("Drone rotation: ", drone.CurrentRotation())
		t.Error("Failed to reset drone rotation")
	} else {
		t.Log("Success: Drone rotation reset correctly")
	}
}

// resetDronePostion resets the position and rotation of the drone
func resetDronePostion(drone *tello.Driver) {
	drone.Forward(0)
	drone.Backward(0)
	drone.Up(0)
	drone.Down(0)
	drone.Left(0)
	drone.Right(0)
	drone.Clockwise(0)
}
