// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package BubbleSort

import (
	"testing"
)

func TestSwap_da24280a8f(t *testing.T) {
	testCases := []struct {
		name     string
		arr      []int
		i        int
		j        int
		expected []int
	}{
		{
			name:     "swap middle elements",
			arr:      []int{1, 2, 3, 4, 5},
			i:        2,
			j:        3,
			expected: []int{1, 2, 4, 3, 5},
		},
		{
			name:     "swap first and last elements",
			arr:      []int{1, 2, 3, 4, 5},
			i:        0,
			j:        4,
			expected: []int{5, 2, 3, 4, 1},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			swap(tc.arr, tc.i, tc.j)

			for i := range tc.arr {
				if tc.arr[i] != tc.expected[i] {
					t.Errorf("Test %s failed: Expected %v but got %v", tc.name, tc.expected, tc.arr)
				}
			}
		})
	}
}
