// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package BubbleSort

import (
	"reflect"
	"testing"
)

func TestSwap_da24280a8f(t *testing.T) {
	type args struct {
		arr []int
		i   int
		j   int
	}
	tests := []struct {
		name string
		args args
		want []int
	}{
		{
			name: "Test 1: Swap elements in the middle of the array",
			args: args{arr: []int{1, 2, 3, 4, 5}, i: 2, j: 3},
			want: []int{1, 2, 4, 3, 5},
		},
		{
			name: "Test 2: Swap first and last elements of the array",
			args: args{arr: []int{1, 2, 3, 4, 5}, i: 0, j: 4},
			want: []int{5, 2, 3, 4, 1},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			swap(tt.args.arr, tt.args.i, tt.args.j)
			if !reflect.DeepEqual(tt.args.arr, tt.want) {
				t.Errorf("swap() = %v, want %v", tt.args.arr, tt.want)
			} else {
				t.Logf("Success: %s", tt.name)
			}
		})
	}
}
