// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package BubbleSort

import (
	"reflect"
	"testing"
)

func TestSwap_da24280a8f(t *testing.T) {
	type args struct {
		arr []int
		i   int
		j   int
	}
	tests := []struct {
		name string
		args args
		want []int
	}{
		{
			name: "Test case 1: Testing with valid indices",
			args: args{
				arr: []int{1, 2, 3, 4, 5},
				i:   1,
				j:   2,
			},
			want: []int{1, 3, 2, 4, 5},
		},
		{
			name: "Test case 2: Testing with same indices",
			args: args{
				arr: []int{1, 2, 3, 4, 5},
				i:   2,
				j:   2,
			},
			want: []int{1, 2, 3, 4, 5},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			swap(tt.args.arr, tt.args.i, tt.args.j)
			if !reflect.DeepEqual(tt.args.arr, tt.want) {
				t.Errorf("swap() = %v, want %v", tt.args.arr, tt.want)
			} else {
				t.Logf("Success! swap() = %v, as expected", tt.args.arr)
			}
		})
	}
}

func swap(arr []int, i, j int) {
	tmp := arr[j]
	arr[j] = arr[i]
	arr[i] = tmp
}
